[package]
name = "envconfig_test_suite"
version = "0.2.0"
authors = ["Sergey Potapov <blake131313@gmail.com>"]

[dependencies]
config = { path = "../config" }
config_derive = { path = "../config_derive" }
